name: demo

on:
  workflow_dispatch:
    inputs:

      num-retries:
        description: "number of retries"
        type: string
        required: true

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4

    - name: "check script"
      run: |
        max_retries=${{ inputs.num-retries }}
        echo "======================================="
        n=0
        while (( $n < $max_retries )); do
            echo "loop $n"
            ./script.sh $n && break
            ((n++))
            sleep 1
        done
        echo "here"
        if (( n == $max_retries )); then
            echo "Command failed after $max_retries attempts."
            exit 1
        fi
        echo "======================================="