name: demo

on:
  workflow_dispatch:
    inputs:

      num_retry:
        description: "number of retries"
        default: 1
        required: true

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4

    - name: "check script"
      shell: bash
      run: |
        #! /bin/bash
        num_retry=${{ inputs.num_retry }}
        max_try=$((num_retry + 1))        

        echo "===============> $max_try"

        set +e

        n=0
        while (( n < max_try )); do
            echo "============================================================================="
            echo "Running testcase"
            echo "============================================================================="
            echo "loop $n"
            ./script.sh $n && break
            ((n++))
        done

        if (( n == max_try )); then
            echo "Command failed after $max_try attempts"
            exit 1
        fi