name: demo

on:
  workflow_dispatch:
    inputs:

      num_retry:
        description: "number of retries"
        default: 1
        required: true

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4

    - name: "check script"
      id: "check-script"
      shell: bash
      run: |
        echo "key=value1" >> "$GITHUB_OUTPUT"
        echo "key=value2" >> "$GITHUB_OUTPUT"
        echo "key=value3" >> "$GITHUB_OUTPUT"
        echo "YEEEESSSSSS" >> "$GITHUB_STEP_SUMMARY"


    - name: "result"
      run: |
        echo "${{ steps.check-script.outputs.key }}"
        echo "Lets check the step summary" >> "$GITHUB_STEP_SUMMARY"
        echo "Passed" >> "$GITHUB_STEP_SUMMARY"

  