name: demo

on:
  workflow_dispatch:
    inputs:

      num_retry:
        description: "number of retries"
        default: 1
        required: true

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4

    - name: "test"
      id: "test"
      shell: bash
      # continue-on-error: true
      run: |
        set +e
        if ./script.sh 0; then
          echo "SUCCEEDED"
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "FAILED"
          echo "status=failure" >> "$GITHUB_OUTPUT"
        fi

    - name: "retry test"
      id: "retry-test"
      shell: bash
      if: ${{ failure() }}
      run: |
        status=${{ steps.test.outputs.status }}
        if [[ "$status" == "success" ]]; then
          exit 0
        fi
        
        num_retry=${{ inputs.num_retry }}
        echo "===============> $num_retry"

        set +e

        n=0
        while (( n < num_retry )); do
            echo "============================================================================="
            echo "Running testcase"
            echo "============================================================================="
            echo "loop $n"
            ./script.sh $n && break
            ((n++))
        done

        if (( n == num_retry )); then
            echo "Command failed after ((num_retry + 1)) attempts"
            exit 1
        fi

    - name: "summary"
      id: "summary"
      shell: "bash"
      run: |
        status=${{ steps.test.outputs.status }}
        if [[ "$status" == "success" ]]; then
          echo "Main execution Passed"
        else
          echo "Retry Passed"
        fi

