name: demo

on:
  workflow_dispatch:
    inputs:

      num_retry:
        description: "number of retries"
        default: 1
        required: true

env:
  ACTION_STATUS: failure

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4

    - name: "main execution"
      id: "main-execution"
      # continue-on-error: true
      run: |
        echo "status=ooops" >> "$GITHUB_OUTPUT"
        # exit 1

    - name: "retries"
      id: "retries"
      if: ${{ failure() }}
      run: |
        echo "========> ${{ steps.main-execution.outputs.status }}"
        echo "HI :)"


    # - name: "check script"
    #   shell: bash
    #   run: |
    #     #! /bin/bash
    #     num_retry=${{ inputs.num_retry }}
    #     max_try=$((num_retry + 1))        

    #     echo "===============> $max_try"

    #     set +e

    #     n=0
    #     while (( n < max_try )); do
    #         echo "============================================================================="
    #         echo "Running testcase"
    #         echo "============================================================================="
    #         echo "loop $n"
    #         ./script.sh $n && break
    #         ((n++))
    #     done

        # if (( n == max_try )); then
        #     echo "Command failed after $max_try attempts"
        #     exit 1
        # fi

# if main fails (X) => retry (conclusion must be based on the overall but main must be marked as failure)