name: Retry

on:
  workflow_call:
    inputs:
      caller-name:
        description: 'file name of the workflow that is requesting a retry'
        required: true
        type: string

      caller-result:
        description: 'final result ("success" or "failure") of the calling workflow'
        required: true
        type: string

      caller-data:
        description: 'JSON-encoded string of inputs needed to retry the caller'
        required: false
        default: '{}'
        type: string

      retry:
        description: 'number of retry attempts allowed for the calling workflow'
        required: true
        default: "0"
        type: string

permissions:
  actions: write


jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7' 
    - name: install dependencies
      run: pip install requests
    - name: retry
      run: python -u .github/retry.py  --token "${{ secrets.GITHUB_TOKEN }}" --retry "${{ inputs.retry }}" --workflow "${{ inputs.caller-name }}" --data "${{ inputs.caller-data }}"

  on-failure:
    needs: retry
    if: ${{ inputs["caller-result"] == "failure" }}  
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo $'\u274C'
      exit 1

  on-success:
    needs: retry
    if: ${{ inputs["caller-result"] == "success" }}  
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo $'\u2705'
      exit 0