name: Retry

on:
  workflow_dispatch:
    inputs:
      attempt:
        description: "max retry count"
        required: false
        default: 2
        type: string


permissions:
  actions: write

jobs:
  retry:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: install python
      id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7' 

    - name: install dependencies
      id: install-dependencies
      run: |
        pip install requests

    - name: dispatch
      id: dispatch
      run: | 
        echo "${{ inputs.attempt }}"
        echo "${{ inputs.attempt || 20 }}"
        python -u retry.py --token "${{ secrets.GITHUB_TOKEN }}" --attempt "${{ inputs.attempt }}" --workflow "retry.yaml" --name "mohammad"

